### ISSUE TITLE
Laby

### ISSUE THREAD

**Issue by aaarmstr** [kidsoncomputers/documentation#17]
Move to programming topic. Include directions if possible.
AA

**Comment by randytate** [comment]
The Raspberry Pi installation package for "laby" installs it into Games.  I don't think it's worth trying to move it because it might complicate updates and/or future installs.  Hopefully students will be able to find it in **Games**.

I was able to run Laby and use Python programming language.  It took a few seconds, but I eventually figured out the objective.  But, I understand the request for documentation, since there isn't much info included in the app.  So I checked out the Laby [website](https://sgimenez.github.io/laby/) and [source code](https://github.com/sgimenez/laby), but still did not find anything useful.  This might just have to be a "try it out and see if you can make it work" type of an app.

I propose we close this.
